#! /usr/bin/env python3
import sys
def main(inputFile):
    print('''{\\rtf1\\ansi\\ansicpg950
{\\fonttbl\\f0\\fnil\\fcharset0 SourceCodePro-Bold;\\f1\\fnil\\fcharset0 SourceCodePro-Regular;}
{\\colortbl;\\red0\\green68\\blue254;}
{\info{\doccomm Generated by SeqToRTF by Steph <admin@hanfubk.com>}}''')
    stdin = open(inputFile,'r')
    for line in stdin:
        result = ''
        if line[:2] == '//':
            result = '\\f1\\cf1 '+line[:-1]+'\\'
        elif line.find(':')>=0:
            result = '\\f0\\cf0 '+line[:line.find(':')+1]+'\n\\f1 '+line[line.find(':')+1:-1]+'\\'
        else:
            result = '\\f1\\cf0 '+line[:-1]+'\\'
        print(result)
    print('}')

if __name__ == '__main__':
    main(sys.argv[1])
